-- =========================================================
-- 江沁钊个人主页 · V3「问题反馈」—— 数据库建表脚本（完整版）
--
-- 怎么用：
--   1) 打开 https://supabase.com/dashboard/project/joqhbooccydgajunwnwf/sql/new
--   2) 把下面【全部内容】粘进去
--   3) 按 Ctrl+Enter（或点右下角 Run）
--   4) 显示 "Success. No rows returned" 就是成功了
--
-- 特点：
--   · 可以重复执行，不会报错
--   · 不会删除或修改你已有的任何数据
--   · 表已存在时自动跳过建表，只把缺的列补上
--   · 这就是修掉页面上 PGRST204 报错的那一步
-- =========================================================


-- ---------- 1. 建表（表已经存在的话，这一段什么都不做） ----------
create table if not exists public.user_feedback (
  id          bigint generated by default as identity primary key,
  name        text,                               -- 访客填的姓名
  device      text,                               -- 电脑 / 手机 / 平板 / 其他设备
  content     text,                               -- 反馈内容
  contact     text,                               -- 备用列（留联系方式用，目前没用上）
  created_at  timestamptz not null default now()   -- 提交时间
);


-- ---------- 2. 给已有的老表补列（你现在的表缺的就是 name） ----------
alter table public.user_feedback add column if not exists name       text;
alter table public.user_feedback add column if not exists device     text;
alter table public.user_feedback add column if not exists content    text;
alter table public.user_feedback add column if not exists contact    text;
alter table public.user_feedback add column if not exists created_at timestamptz not null default now();


-- ---------- 3. 打开行级安全（RLS） ----------
alter table public.user_feedback enable row level security;


-- ---------- 4. 允许匿名访客（anon）"写入" ----------
grant usage on schema public to anon;
grant insert on table public.user_feedback to anon;


-- ---------- 5. 写策略：只放行"新增反馈" ----------
--     访客只能写；读不到、改不了、删不掉任何一条反馈。
--     ⚠️ 不要为了"想在网页上读数据"再加一条 select 策略 ——
--        反馈内容不该被任何匿名访客翻看。要看数据请用左边的 Table Editor。
drop policy if exists "anon can insert feedback" on public.user_feedback;
create policy "anon can insert feedback"
  on public.user_feedback
  for insert
  to anon
  with check (true);


-- ---------- 6. 自查：把这三段的结果对照一下 ----------

-- 6.1 现在的列有哪些（应该能看到 name）
select column_name, data_type
  from information_schema.columns
 where table_schema = 'public' and table_name = 'user_feedback'
 order by ordinal_position;

-- 6.2 策略有哪些（应该能看到 anon can insert feedback / INSERT / {anon}）
select policyname, cmd, roles
  from pg_policies
 where schemaname = 'public' and tablename = 'user_feedback';

-- 6.3 表里现在有几行（用来确认测试数据在不在）
select count(*) as 当前行数 from public.user_feedback;
