-- ============================================================
--  江沁钊个人主页 · V3「问题反馈」数据库 —— 一键脚本
--
--  用法：整段复制 → 粘到 Supabase SQL Editor → Ctrl+Enter
--        看到 "Success. No rows returned" 就说明跑完了
--
--  直达地址：
--  https://supabase.com/dashboard/project/joqhbooccydgajunwnwf/sql/new
--
--  这段脚本会做四件事：
--    ① 建表 / 给老表补上缺的列（修掉页面上的 PGRST204）
--    ② 配置权限和 RLS 策略，让访客只能"提交"，不能读取别人的反馈
--    ③ 清掉排障时留下的 3 行测试数据
--    ④ 最后自查，把结果给你看
--
--  安全说明：可以重复执行，不会报错，除了第 ③ 步的测试数据以外
--            不会删除任何东西，也不会改动你已有的表结构。
-- ============================================================


-- ---------- ① 建表（表已经存在的话，这一段什么都不做） ----------
create table if not exists public.user_feedback (
  id          bigint generated by default as identity primary key,
  name        text,                                -- 访客填的姓名
  device      text,                                -- 电脑 / 手机 / 平板 / 其他设备
  content     text,                                -- 反馈内容
  contact     text,                                -- 备用列（留联系方式用，目前没用上）
  created_at  timestamptz not null default now()    -- 提交时间
);

-- 给已有的老表补列（你之前缺的就是 name）
alter table public.user_feedback add column if not exists name       text;
alter table public.user_feedback add column if not exists device     text;
alter table public.user_feedback add column if not exists content    text;
alter table public.user_feedback add column if not exists contact    text;
alter table public.user_feedback add column if not exists created_at timestamptz not null default now();


-- ---------- ② 权限与安全策略 ----------
alter table public.user_feedback enable row level security;

-- 允许匿名访客（anon）提交
grant usage  on schema public to anon;
grant insert on table  public.user_feedback to anon;

-- 只放行"新增"：访客读不到、改不了、删不掉任何一条反馈。
-- ⚠️ 不要为了"想在网页上显示反馈"再加一条 select 策略——
--    反馈内容不该被任何匿名访客翻看。要看数据用左侧 Table Editor。
drop policy if exists "anon can insert feedback" on public.user_feedback;
create policy "anon can insert feedback"
  on public.user_feedback
  for insert
  to anon
  with check (true);


-- ---------- ③ 看看现有数据，然后清掉测试数据 ----------
-- 下面这句会列出表里现在的内容，你可以先看一眼
select id, device, content, created_at
  from public.user_feedback
 order by created_at;

-- 清空：现在表里这 3 行都是排障时插入的测试数据（你的页面只在本地跑过，
-- 不可能收到真实反馈）。以后要清空整张表，同样用这一句。
delete from public.user_feedback;


-- ---------- ④ 自查：对照下面三块结果 ----------
-- 4.1 列清单 —— 应该能看到 name
select column_name, data_type
  from information_schema.columns
 where table_schema = 'public' and table_name = 'user_feedback'
 order by ordinal_position;

-- 4.2 策略清单 —— 应该看到 anon can insert feedback | INSERT | {anon}
select policyname, cmd, roles
  from pg_policies
 where schemaname = 'public' and tablename = 'user_feedback';

-- 4.3 行数 —— 应该是 0
select count(*) as 当前行数 from public.user_feedback;
